hotels/routes/web.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('main');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::view('/hotelvue', 'hotels.hotelvue')->name('hotelvue');

Route::prefix('hotel')->group(function () {
    Route::name('hotel.')->group(function() {
        Route::get('new', 'HotelController@create')->name('new');
        Route::post('store', 'HotelController@store')->name('store');
        Route::get('index', 'HotelController@index')->name('index');
        Route::get('statement', 'HotelController@statement')->name('statement');
        Route::get('{id}', 'HotelController@show')->name('show');
        Route::get('edit/{id}', 'HotelController@edit')->name('edit');
        Route::delete('{id}', 'HotelController@destroy')->name('delete');
        Route::get('index/search', 'HotelController@search')->name('search');
        Route::post('copy/{id}', 'HotelController@copy')->name('copy');
    });
});

Route::prefix('tour')->group(function () {
    Route::name('tour.')->group(function() {
        Route::get('new', 'TourController@create')->name('new');
        Route::post('store', 'TourController@store')->name('store');
        Route::get('index', 'TourController@index')->name('index');
        Route::get('statement', 'TourController@statement')->name('statement');
        Route::post('search', 'TourController@search')->name('search');
        Route::get('{id}', 'TourController@show')->name('show');
        Route::get('edit/{id}', 'TourController@edit')->name('edit');
        Route::delete('{id}', 'TourController@destroy')->name('delete');
    });
});

Route::prefix('comment')->group(function () {
    Route::post('store', 'CommentController@store')->name('comment.store');
});

hotels/app/Models/Tour.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Traits\ModelTrait;

class Tour extends Model
{
    use HasFactory,
        SoftDeletes,
        ModelTrait;
    
    const OWN_SCOPE = 1;
    const BREAKFAST = 2;
    const BREAKFAST_AND_DINNER = 3;
    const ALL_INCLUSIVE = 4;

    const PAGINATION = 4;
    
    public static $foods = [
        self::OWN_SCOPE => 'Własny zakres',
        self::BREAKFAST => 'Śniadania',
        self::BREAKFAST_AND_DINNER => 'Śniadania i kolacje',
        self::ALL_INCLUSIVE => 'All inclusive'
    ];
    
    protected $table = 'tours';
    //protected $hidden = ['updated_at', 'deleted_at'];
    protected $fillable = [
        'price',
        'date_from',
        'date_to',
        'food',
        'hotel_id',
    ];
    protected $sortable = ['date_from', 'date_to'];
    
    public function hotel()
    {
        return $this->belongsTo('App\Models\Hotel');
    }
}

hotels/app/Http/Controllers/TourController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Hotel;
use App\Models\Tour;
use App\Http\Requests\TourChangeRequest;
use Illuminate\Pagination\Paginator;

class TourController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tours = Tour::with('hotel')->paginate(Tour::PAGINATION);
        $foods = Tour::$foods;

        return view('tours/index', ['tours' => $tours, 'foods' => $foods]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $hotels = Hotel::all();
        $foods = Tour::$foods;

        return view('tours/form', ['hotels' => $hotels, 'foods' => $foods]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TourChangeRequest $request)
    {
        $request->validated();
        $input = $request->all();
        $id = isset($input['id']) ? $input['id'] : null;
        Tour::createOrUpdate($input, $id);

        return redirect('tour/index')->with('mssg', 'Thanks for your order!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $tour = Tour::with('hotel')->get()->find($id);

        return view('tours/tour', ['tour' => $tour]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tour = Tour::find($id);
        $hotels = Hotel::all();
        $foods = Tour::$foods;

        return view('tours/form', ['tour' => $tour, 'hotels' => $hotels, 'foods' => $foods]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Tour::destroy($id);
        return redirect('tour/index');
    }

    /**
     * Function gets data to statement
     * 
     */
    public function statement() {
        $tours = Tour::with('hotel')->get()->toArray();

        return view('tours/statement', ['tours' => $tours]);
    }

    /**
     * Function returns filtered data
     * 
     * @param  \Illuminate\Http\Request  $request
     */
    public function search(Request $request) {
        $input = $request->all();
        $food = $input['food'];
        $page = isset($input['page']) ? $input['page'] : 0;

        Paginator::currentPageResolver(function () use ($page) {
            return $page;
        });

        $tours = Tour::with('hotel');

        if(!empty($food)) {
            $tours->where('food', $food);
        }
        $tours = $tours->paginate(Tour::PAGINATION);

        return view('tours/tour_list', ['tours' => $tours]);
    }
}

hotels/resources/views/tours/form.blade.php
@extends('layouts.app')

@section('content')
        <div class="container">
        <form class="form-horizontal"  action="{{route('tour.store')}}" method="post">
            @csrf
            <div class="form-group">
                <label for="price" class="control-label col-sm-2" >{{ __('TOUR')['PRICE'] }}</label>
                <div class="col-sm-12">
                     <input type="number" name="price" id="price" step="0.01" class="form-control"
                            @if(old('price') != null )
                                value = "{{ old('price') }}"
                            @else
                                @isset($tour->price)
                                    value="{{$tour->price}}"
                                @endisset
                            @endif
                        required/>
                @error('price')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
                </div>
            </div>
            
            
            <div class="form-group row no-gutters">
                <div class="form-group col-sm-6">
                <label for="date_from" class="control-label col-sm-12">{{ __('TOUR')['DATE_FROM'] }}</label>
                    <div class="col-sm-12">
                        <input type="date" name="date_from" id="date_from" class="form-control @error('date_from') is-invalid @enderror"
                        @if(old('date_from') != null )
                            value = "{{ old('date_from') }}"
                        @else
                            @isset($tour->date_from)
                                value="{{$tour->date_from}}"
                            @endisset
                        @endif
                       required />
                        @error('date_from')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
                
                <div class="form-group col-sm-6">
                <label for="date_to" class="control-label col-sm-12">{{ __('TOUR')['DATE_TO'] }}</label>
                <div class="col-sm-12">
                <input type="date" name="date_to" id="date_to" class="form-control @error('date_to') is-invalid @enderror col-sm-12"
                        @if(old('date_to') != null )
                            value = "{{ old('date_to') }}"
                        @else
                            @isset($tour->date_to)
                                value="{{$tour->date_to}}"
                            @endisset
                        @endif
                       required />
                    @error('date_to')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
                </div>
                </div>             
            </div>
                    
            <div class="form-group">
                <label for="hotel_id" class="control-label col-sm-2">{{ __('TOUR')['HOTEL'] }}</label>
                <div class="col-sm-12">
                    <select name="hotel_id" id="hotel_id" class="form-control">
                        @foreach($hotels as $hotel)
                        <option value="{{$hotel->id}}"
                                @isset($tour->hotel_id)
                                    @if ($hotel->id == $tour->hotel_id)
                                    selected
                                    @endif
                            @endisset>{{$hotel->name}}
                                </option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="food" class="control-label col-sm-2" >{{ __('TOUR')['FOOD'] }}</label>
                <div class="col-sm-12">
                    <select name="food" id="food" class="form-control">
                        @foreach($foods as $key => $value)
                        <option value="{{$key}}"
                                @isset($tour->food)
                                    @if ($key == $tour->food)
                                    selected
                                    @endif
                                @endisset>
                               {{$value}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
             @isset($tour->id)
                <div class="form-group">
                <input type="hidden" value="{{$tour->id}}" name="id" id="id" class="form-control"/>
            </div>
            @endisset
            <div class="form-group col-sm-12">
                <input type="submit" value="{{ __('FORMS')['SUBMIT'] }}" class="btn btn-secondary col-sm-12"/>
            </div>
        </form>
            </div>

@endsection

hotels/resources/views/tours/index.blade.php
@extends('layouts.app')

@section('content')
{{ Breadcrumbs::render() }}
<div class="container">
    <h3>{{ trans('tour.list') }} </h3>
    <div class="form-group">
        <label for="food">{{ trans('tour.foods') }} </label>
        <select name="food" id="food">
            <option value="" selected> {{ trans('tour.food_default') }}</option>
            @foreach ($foods as $key => $food)
            <option value="{{$key}}">{{$food}}</option>
            @endforeach
        </select>
    </div>

    <div id="tours">
        @include('tours.tour_list', ['tours' => $tours])
    </div>
</div>

@endsection

@push('scripts')
<script>
    $(document).ready(function() {

        $('#food').on('change', function() {
            var food = $(this).val();
            var searchRoute = '{{ route("tour.search") }}';

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.ajax({
                url: searchRoute,
                method: "POST",
                data: {
                    food: food
                },
                success: function(response) {
                    $('#tours').html(response);

                }
            });
        })

        $('.pagination a').bind('click', function (e) {
            e.preventDefault();
            
            var page = $(this).text();
            
            var searchRoute = '{{ route("tour.search") }}';
            console.log('test', page, searchRoute);
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.ajax({
                url: searchRoute,
                method: "POST",
                data: {
                    food : '0',
                    page: page
                },
                success: function(response) {
                    $('#tours').html(response);
                }
            });
        })
        $('#tours').on('click', '.page-item, .pagination a', function (e) {
            e.preventDefault();
            
            var page = $(this).text();
            
            var searchRoute = '{{ route("tour.search") }}';
            console.log('testitem', page, searchRoute);
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.ajax({
                url: searchRoute,
                method: "POST",
                data: {
                    food : '0',
                    page: page
                },
                success: function(response) {
                    $('#tours').html(response);
                }
            });

        })
    });
</script>
@endpush

hotels/resources/views/tours/statement.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <table id="table_id" class="display">
    </table>
</div>

@endsection

@push('scripts')
<script>
    $(document).ready(function() {

        var data = @json($tours);
        var foods = @json(App\Models\Tour::$foods);
        var tableId = "#" + "table_id";

        var columns = [
            {data: 'id', title: 'ID'},
            {data: 'price', title: 'Cena', render: function ( data, type, row ) {
                return '$' + data;
            }},
            {data: 'date_from', title: 'Data od'},
            {data: 'date_to', title: 'Data do'},
            {data: 'food', title: 'Wyzywienie', render: function ( data, type, row ) {
                return foods[data];
            }},
            {data: 'hotel.name', title: 'Hotel'}
        ]

        $(tableId).DataTable({
            data: data,
            columns: columns
        });
    });
</script>
@endpush

hotels/resources/views/tours/tour.blade.php
@extends('layouts.app')

@section('pageTitle', $tour['hotel']['name'])

@section('content')
{{ Breadcrumbs::render() }}

<div class="container">
    <h3>{{ trans('tour.tour_id', ['id' => $tour->id])}}</h3>
    <ul>
        <li>{{ trans('tour.price') }} : ${{ $tour->price }}</li>
        <li>{{ $tour->date_from  }} - {{ $tour->date_to }}</li>
        <li>{{ trans('tour.foods')  }} - {{ App\Models\Tour::$foods[$tour->food] }}</li>
        <li>{{ $tour->hotel->name }} </li>
        <li>{{ trans('hotel.city') }} - {{$tour->hotel->city }} </li>
        <li>{{ trans('hotel.country') }} - {{$tour->hotel->country }}</li>
    </ul>
</div>

@endsection

hotels/resources/views/tours/tour_list.blade.php
@foreach($tours as $tour)
<fieldset class="border p-2 mb-3">
    <h5>{{ trans('tour.tour_id', ['id' => $tour->id]) }} </h5>
    <ul>
        <li>{{ trans('tour.price') }} : ${{ $tour->price }}</li>
        <li>{{ $tour->date_from  }} - {{ $tour->date_to }}</li>
        <li>{{ trans('tour.foods')  }} - {{ App\Models\Tour::$foods[$tour->food] }}</li>
        <li>{{ $tour->hotel->name }} </li>
    </ul>
    <div class="row no-gutters">
        <div class="col-sm-2 mr-2">
            <a href="{{ route('tour.show', $tour->id) }}" class="btn btn-info col-sm-12 mb-2"> {{ __('FORMS')['DETAILS'] }}</a>
        </div>
        <div class="col-sm-1 mr-2">
            <a href="{{ route('tour.edit', $tour->id) }}" class="btn btn-info col-sm-12 mb-2"><i class="fa fa-pencil-square-o"></i></a>
        </div>
        <div class="col-sm-1 mr-2">
            <form action="{{ route('tour.delete', $tour->id) }}" method="post">
                @csrf
                @method('DELETE')
                <button class="btn btn-danger col-sm-12 mb-2"><i class="fa fa-trash"></i></button>
            </form>
        </div>
    </div>
</fieldset>
@endforeach

{{ $tours->links("pagination::bootstrap-4") }}