hotels/routes/web.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('main');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::view('/hotelvue', 'hotels.hotelvue')->name('hotelvue');

Route::prefix('hotel')->group(function () {
    Route::name('hotel.')->group(function() {
        Route::get('new', 'HotelController@create')->name('new');
        Route::post('store', 'HotelController@store')->name('store');
        Route::get('index', 'HotelController@index')->name('index');
        Route::get('statement', 'HotelController@statement')->name('statement');
        Route::get('{id}', 'HotelController@show')->name('show');
        Route::get('edit/{id}', 'HotelController@edit')->name('edit');
        Route::delete('{id}', 'HotelController@destroy')->name('delete');
        Route::get('index/search', 'HotelController@search')->name('search');
        Route::post('copy/{id}', 'HotelController@copy')->name('copy');
    });
});

Route::prefix('tour')->group(function () {
    Route::name('tour.')->group(function() {
        Route::get('new', 'TourController@create')->name('new');
        Route::post('store', 'TourController@store')->name('store');
        Route::get('index', 'TourController@index')->name('index');
        Route::get('statement', 'TourController@statement')->name('statement');
        Route::post('search', 'TourController@search')->name('search');
        Route::get('{id}', 'TourController@show')->name('show');
        Route::get('edit/{id}', 'TourController@edit')->name('edit');
        Route::delete('{id}', 'TourController@destroy')->name('delete');
    });
});

Route::prefix('comment')->group(function () {
    Route::post('store', 'CommentController@store')->name('comment.store');
});

hotels/app/Models/Hotel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Dyrynda\Database\Support\CascadeSoftDeletes;
use App\Traits\ModelTrait;

class Hotel extends Model
{
    use HasFactory,
        softDeletes,
        ModelTrait,
        CascadeSoftDeletes;
    
    const PAGINATION = 8;

    protected $table = 'hotels';
    protected $hidden = ['created_at', 'deleted_at', 'updated_at'];
    protected $cascadeDeletes = ['tours', 'comments'];
    protected $fillable = [
        'name',
        'country',
        'city'
    ];
    
    public function tours()
    {
        return $this->hasMany(Tour::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

hotels/app/Http/Controllers/Api/HotelController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Hotel;
use App\Http\Requests\HotelChangeRequest;

class HotelController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    /**
     * @OA\Get(
     *   path="/api/hotels",
     *   summary="Lista wszystkich hoteli",
     *   @OA\Response(
     *     response=200,
     *     description="Wszystkie hotele"
     *   ),
     *   @OA\Response(
     *     response="default",
     *     description="Błąd"
     *   )
     * )
     */
    public function index()
    {
        $hotels = Hotel::all();
        $success = true;
        return response()->json(compact('success', 'hotels'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(HotelChangeRequest $request)
    {
        $request->validated();
        $input = $request->all();
        Hotel::create($input);
        
        $success = true;
        $message = 'Pomyślnie dodano hotel';
        return response()->json(compact('success', 'message'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    /**
     * @OA\Get(
     *   path="/api/hotel/{id}",
     *   summary="Wybrany hotel",
     *   @OA\Response(
     *     response=200,
     *     description="Wybrany hotel"
     *   ),
     * @OA\Parameter(
     *    description="Hotel id",
     *    in="path",
     *    name="id",
     *    required=true,
     *    @OA\Schema(
     *       type="integer",
     *       format="int64"
     *    )
     * ),
     *   @OA\Response(
     *     response="default",
     *     description="Błąd"
     *   )
     * )
     */
    public function show($id)
    {
        $success = true;
        $hotel = Hotel::find($id);
        if (empty($hotel))
        {
            $success = false;
            $error = 'Hotel nie został znaleziony';
        }  
        
        return response()->json(compact('success', 'hotel'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

hotels/app/Http/Controllers/HotelController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Hotel;
use App\Http\Requests\HotelChangeRequest;

class HotelController extends Controller
{
    
    public function __construct()
    {
        $this->middleware('auth');   
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $hotels = Hotel::paginate(Hotel::PAGINATION);
        return view('hotels/index', ['hotels' => $hotels]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('hotels/form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(HotelChangeRequest $request)
    {
        $request->validated();
        $input = $request->all();
        $id = isset($input['id']) ? $input['id'] : null;
        Hotel::createOrUpdate($input, $id);
        return redirect('hotel/index');
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //dd(Hotel::with('comments')->get()->find($id)->toArray());
        $hotel = Hotel::with('comments')->get()->find($id);
        //dd($hotel);
        return view('hotels/hotel', ['hotel' => $hotel]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $hotel = Hotel::find($id);
        return view('hotels/form', ['hotel' => $hotel]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Hotel::destroy($id);
        return redirect('hotel/index');
    }
    
    /**
     * Search hotel by name
     *
     * @param  str  $name
     * @return \Illuminate\Http\Response
     */
    public function search()
    {
        $name = request('name');

        $hotels = Hotel::where('name', 'like', '%'.$name.'%')->paginate(Hotel::PAGINATION);
        return view('hotels/index', ['hotels' => $hotels]);
    }
    
    /**
     * Copy hotel
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function copy($id)
    {
        //$hotel = Hotel::find($id)->toArray()->pluck('name');
        //$hotel = Hotel::select('name', 'country', 'city')->where('id', $id)->get()->toArray();
        $hotel = Hotel::find($id)->toArray();
        unset($hotel['id']);
        Hotel::create($hotel);
        return redirect('hotel/index');
    }


    public function statement() {
        $hotels = Hotel::all()->toArray();

        //dd($tours);
        return view('hotels/statement', ['hotels' => $hotels]);
    }
}

hotels/resources/views/hotels/form.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <form class="form-horizontal" action="{{route('hotel.store')}}" method="post">
        @csrf
        <div class="form-group">
            <label for="name" class="col-sm-4">{{ __('HOTEL')['NAME'] }}</label>
            <div class="col-sm-12">
                <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror" @if(old('name') !=null ) value="{{ old('name') }}" @else @isset($hotel->name)
                value="{{$hotel->name}}"
                @endisset
                @endif
                required/>
                @error('name')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>
        <div class="form-group">
            <label for="city" class="col-sm-4">{{ __('HOTEL')['CITY'] }}</label>
            <div class="col-sm-12">
                <input type="text" name="city" id="city" class="form-control @error('city') is-invalid @enderror" @if(old('city') !=null ) value="{{ old('city') }}" @else @isset($hotel->city)
                value="{{$hotel->city}}"
                @endisset
                @endif
                required />
                @error('city')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>
        <div class="form-group">
            <label for="country" class="col-sm-4">{{ __('HOTEL')['COUNTRY'] }}</label>
            <div class="col-sm-12">
                <input type="text" name="country" id="country" class="form-control @error('country') is-invalid @enderror" @if(old('country') !=null ) value="{{ old('country') }}" @else @isset($hotel->country)
                value="{{$hotel->country}}"
                @endisset
                @endif
                required />
                @error('country')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </div>
        </div>
        <div class="form-group col-sm-12">
            <input type="submit" value="{{ __('FORMS')['SUBMIT'] }}" class="form-control" />
        </div>
        @isset($hotel->id)
        <div class="form-group">
            <input type="hidden" value="{{$hotel->id}}" name="id" id="id" class="form-control" />
        </div>
        @endisset
    </form>
</div>




@endsection

hotels/resources/views/hotels/hotel.blade.php
@extends('layouts.app')

@section('pageTitle', $hotel['name'])

@section('content')
        <div class="container">

            <h3>{{ $hotel->name }}</h3>

            <ul>
                <li>{{ $hotel->city }}</li>
                <li>{{ $hotel->country }}</li>
            </ul>

            <div class="comments">
                <h4>{{__('COMMENT')['COMMENTS']}}</h4>
                @foreach ($hotel['comments'] as $comment)
                    <p>Treść komentarza: {{ $comment['text'] }}</p>
                @endforeach
            </div>

            <div class="form-group">
                <form id="commentForm">
                    @csrf
                    <label class="col-12">Dodaj komentarz:</label>
                    <input class="col-12" type="textarea" name="text" id="text" style="height: 80px; margin-bottom: 10px;"/>
                    <span class="text-danger" id="textError"></span>
                    <button class="btn btn-success savebtn col-12" type="submit">Dodaj komentarz</button>
                </form>
            <div>
        </div>

        



@endsection

@push('scripts')

<script type="text/javascript" src="{{ URL::asset('js/HotelController.js') }}"></script>

    <script>
        $(document).ready(function () {
            $('#commentForm').on('submit', function (e) {
                e.preventDefault();
                var hotelId = @json($hotel['id']);
                var storeRoute = '{{ route("comment.store") }}';
                addComment(hotelId, storeRoute);
            })

        })

    </script>
@endpush

hotels/resources/views/hotels/hotelvue.blade.php
@extends('layouts.app')

@section('content')

<div id="app">
    <front-page></front-page>
</div>
        

 
@endsection

<script src="{{ mix('js/app.js') }}"></script>

hotels/resources/views/hotels/index.blade.php
@extends('layouts.app')

@section('content')
        <div class="container">
            <h3>{{ __('HOTEL')['LIST'] }}</h3>
                <div class="form-group">
                    <form action="{{route('hotel.search')}}" method="get" class="form-inline">
                        <input type="text" name="name" id="name" class="form-control col-sm-3 mr-sm-3" value = "{{ app('request')->input('name') }}" required/>
                        <button class="btn btn-primary col-sm-1 mr-sm-3"><i class="fa fa-search"></i></button>
                        <a href="{{ URL::route('hotel.index') }}" class="btn btn-danger col-sm-1"><i class="fa fa-close"></i></a>
                    </form>
                </div>
        @foreach($hotels as $hotel)
            <fieldset class="border p-2 mb-3">
                <h4 class="form-label mr-2 mb-2">{{ $hotel['name'] }}</h4>                
                <div class="row no-gutters">
                    <div class="col-sm-2 mr-2">
                        <a href="{{ URL::route('hotel.show', $hotel['id']) }}" class="btn btn-info col-sm-12 mb-2"> {{ __('FORMS')['DETAILS'] }}</a>
                    </div>
                    <div class="col-sm-1 mr-2">
                        <a href="{{ URL::route('hotel.edit', $hotel['id']) }}" class="btn btn-info col-sm-12 mb-2"><i class="fa fa-pencil-square-o"></i></a>
                    </div>
                    <div class="col-sm-1 mr-2">
                        <form action="{{ route('hotel.copy', $hotel['id']) }}" method="post">
                            @csrf
                            <button class="btn btn-info col-sm-12 mb-2"><i class=" fa fa-files-o"></i></button>
                        </form>
                    </div>
                    <div class="col-sm-1 mr-2">
                        <form action="{{ route('hotel.delete', $hotel['id']) }}" method="post">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger col-sm-12 mb-2"><i class="fa fa-trash"></i></button>
                        </form>
                    </div>
                </div>
            </fieldset>
        @endforeach
            {{ $hotels->withQueryString()->links("pagination::bootstrap-4") }}

           
        </div>

 
@endsection

hotels/resources/views/hotels/statement.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <table id="table_id" class="display">
    </table>
</div>

@endsection

@push('scripts')

<script type="text/javascript" src="{{ URL::asset('js/HotelController.js') }}"></script>

<script>
    $(document).ready(function () {
        var data = @json($hotels);

        var dataTable = new HotelClass(data, 'table_id');
        dataTable.initTable();
    })


</script>


@endpush